port select --set ansible py313-ansible
port select --set black black313
port select --set clang mp-clang-19
port select --set cython cython313
port select --set docutils py313-docutils
port select --set gcc mp-gcc15
port select --set hatchling py313-hatchling
port select --set llvm mp-llvm-19
port select --set mpi openmpi-clang19-fortran
port select --set mypy mypy313
port select --set pip pip313
port select --set pip3 pip313
port select --set pygments py313-pygments
port select --set pytest pytest313
port select --set python python313
port select --set python3 python313
port select --set ruby ruby33
port select --set sphinx py313-sphinx
port select --set virtualenv virtualenv313
